### ISSUE TITLE
Research not showing up

### ISSUE THREAD

**Issue by mooklepticon** [s-lindenau/AutoDeployDestroyers#1]
I can't find the research option for the mod. Attached are screen shots of my research screen and my mod list.
![20160519062015_1](https://cloud.githubusercontent.com/assets/19435974/15391967/d300fc14-1d89-11e6-8eaf-dbbb06d669ab.jpg)
![20160519062016_1](https://cloud.githubusercontent.com/assets/19435974/15391968/d3033966-1d89-11e6-94c6-1a5ce5164bb5.jpg)

![20160519062119_1](https://cloud.githubusercontent.com/assets/19435974/15391979/e8545214-1d89-11e6-9c0f-b3886d9400cd.jpg)

**Comment by mooklepticon** [comment]
Er. I just noticed I've got 0.1.1 and the latest is 0.1.2. I'll report back after I update.

**Comment by s-lindenau** [comment]
That is probably it. Release notes are on the forum page, and the power armor related stuff was added in 0.1.2 :).

I've now also added the release notes directly on the releases here, to make it more clear.

**Comment by mooklepticon** [comment]
Research showed up on 0.1.2!
